---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellonode
  annotations:
    flux.weave.works/automated: 'true'
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: hellonode
    spec:
      containers:
      - name: hellonode
        image: docker.io/rigvedspatki/hello-node:v3
        ports:
        - containerPort: 80
